Scandinaver\Learn\Domain\Model\Card:
  type: entity
  table: cards
  indexes:
    word_id:
      columns:
        - word_id
    translate_id:
      columns:
        - translate_id
  id:
    id:
      type: integer
      scale: 0
      length: null
      unique: false
      nullable: false
      precision: 0
      id: true
      generator:
        strategy: IDENTITY
  fields:
    createdAt:
      type: datetime
      scale: 0
      length: null
      unique: false
      nullable: true
      precision: 0
      column: created_at
      gedmo:
        timestampable:
          on: create
    updatedAt:
      type: datetime
      scale: 0
      length: null
      unique: false
      nullable: true
      precision: 0
      column: updated_at
      gedmo:
        timestampable:
          on: update
    type:
      type: integer
      unique: false
      nullable: false
      column: type
  manyToOne:
    word:
      targetEntity: Scandinaver\Learn\Domain\Model\Word
      cascade: ["persist", "merge"]
      fetch: EAGER
      joinColumns:
        word_id:
          referencedColumnName: id
      orphanRemoval: false
    translate:
      targetEntity: Scandinaver\Learn\Domain\Model\Translate
      cascade: ["persist", "merge"]
      fetch: EAGER
      mappedBy: null
      inversedBy: null
      joinColumns:
        translate_id:
          referencedColumnName: id
      orphanRemoval: false
    language:
      targetEntity: Scandinaver\Common\Domain\Model\Language
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        language_id:
          referencedColumnName: id
      orphanRemoval: false
  oneToMany:
    examples:
      targetEntity: Scandinaver\Learn\Domain\Model\Example
      cascade: ["persist", "merge"]
      fetch: EAGER
      mappedBy: card
      inversedBy: null
      joinColumns:
        card_id:
          referencedColumnName: id
      orphanRemoval: true
      orderBy: null
  #manyToMany:
  #    assets:
  #        targetEntity:  Scandinaver\Learn\Domain\Model\Asset
  #        joinTable:
  #            name: asset_cards
  #            joinColumns:
  #                asset_id:
  #                    referencedColumnName: id
  #            inverseJoinColumns:
  #                card_id:
  #                    referencedColumnName: id
  #


  lifecycleCallbacks: {  }
