Scandinaver\Learn\Domain\Model\Result:
    type: entity
    table: asset_user
    indexes:
        language_id:
            columns:
                - language_id
        user_id:
            columns:
                - user_id
        asset_id:
            columns:
                - asset_id
    id:
        id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: IDENTITY
    fields:
        result:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        assetId:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            column: asset_id
        createdAt:
            type: datetime
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: created_at
        updatedAt:
            type: datetime
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: updated_at
    manyToOne:
        asset:
            targetEntity: Scandinaver\Learn\Domain\Model\Asset
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: results
            joinColumns:
                asset_id:
                    referencedColumnName: id
            orphanRemoval: false
        user:
            targetEntity: Scandinaver\User\Domain\Model\User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: results
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
        language:
            targetEntity: Scandinaver\Common\Domain\Model\Language
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: results
            joinColumns:
                language_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
