Scandinaver\Learn\Domain\Model\Result:
  type: entity
  table: result_asset
  indexes:
    user_id:
      columns:
        - user_id
    asset_id:
      columns:
        - asset_id
  id:
    id:
      type: integer
      scale: 0
      length: null
      unique: false
      nullable: false
      precision: 0
      id: true
      generator:
        strategy: IDENTITY
  fields:
    result:
      type: integer
      scale: 0
      length: null
      unique: false
      nullable: false
      precision: 0
    createdAt:
      type: datetime
      scale: 0
      length: null
      unique: false
      nullable: true
      precision: 0
      column: created_at
      gedmo:
        timestampable:
          on: create
    updatedAt:
      type: datetime
      scale: 0
      length: null
      unique: false
      nullable: true
      precision: 0
      column: updated_at
      gedmo:
        timestampable:
          on: update
  manyToOne:
    asset:
      targetEntity: Scandinaver\Learn\Domain\Model\Asset
      cascade:
        - persist
      fetch: LAZY
      mappedBy: null
      inversedBy: results
      joinColumns:
        asset_id:
          referencedColumnName: id
      orphanRemoval: false
    user:
      targetEntity: Scandinaver\User\Domain\Model\User
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: tests
      joinColumns:
        user_id:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: {  }
