Scandinaver\Blog\Domain\Entity\Comment:
  type: entity
  table: comment
  id:
    id:
      type: integer
      nullable: false
      id: true
      generator:
        strategy: IDENTITY
  fields:
    text:
      type: text
      unique: false
      nullable: true
    createdAt:
      type: datetime
      unique: false
      nullable: false
      column: created_at
      gedmo:
        timestampable:
          on: create
    updatedAt:
      type: datetime
      unique: false
      nullable: true
      column: updated_at
      gedmo:
        timestampable:
          on: update
  manyToOne:
    post:
      targetEntity: Scandinaver\Blog\Domain\Entity\Post
      cascade: { }
      fetch: LAZY
      mappedBy: null
      inversedBy: comments
      joinColumns:
        post_id:
          referencedColumnName: id
      orphanRemoval: false
    user:
      targetEntity: Scandinaver\User\Domain\Entity\User
      cascade: { }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        user_id:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: { }
