Scandinaver\User\Domain\Entity\OauthAccessToken:
  type: entity
  table: oauth_access_tokens
  indexes:
    user_id_token_index:
      columns:
        - user_id
  id:
    id:
      type: string
      length: 100
      unique: false
      nullable: false
      id: true
  fields:
    userId:
      type: integer
      unique: false
      nullable: true
      column: user_id
    clientId:
      type: integer
      unique: false
      nullable: false
      column: client_id
    name:
      type: string
      length: 255
      unique: false
      nullable: true
    scopes:
      type: text
      unique: false
      nullable: true
    revoked:
      type: boolean
      unique: false
      nullable: false
    createdAt:
      type: datetime
      unique: false
      nullable: false
      column: created_at
    updatedAt:
      type: datetime
      unique: false
      nullable: true
      column: updated_at
    expiresAt:
      type: datetime
      unique: false
      nullable: true
      column: expires_at
  lifecycleCallbacks: { }
