Scandinaver\User\Domain\Entity\OauthRefreshToken:
  type: entity
  table: oauth_refresh_tokens
  indexes:
    access_token_index:
      columns:
        - access_token_id
  id:
    id:
      type: string
      length: 100
      unique: false
      nullable: false
      id: true
  fields:
    accessTokenId:
      type: string
      length: 100
      unique: false
      nullable: false
      column: access_token_id
    revoked:
      type: boolean
      unique: false
      nullable: false
    expiresAt:
      type: datetime
      unique: false
      nullable: true
      column: expires_at
  lifecycleCallbacks: { }
