Scandinaver\User\Domain\Entity\User:
  type: entity
  table: user
  indexes:
    restore_link:
      columns:
        - restore_link
    last_online:
      columns:
        - last_online
  uniqueConstraints:
    email:
      columns:
        - email
  id:
    id:
      type: integer
      nullable: false
      id: true
      generator:
        strategy: IDENTITY
  fields:
    login:
      type: string
      length: 255
      unique: true
      nullable: false
    email:
      type: string
      length: 255
      unique: true
      nullable: false
    raisedTo:
      type: datetime
      unique: false
      nullable: true
      column: raised_to
    name:
      type: string
      length: 255
      unique: false
      nullable: true
    photo:
      type: text
      unique: false
      nullable: true
    restoreLink:
      type: string
      length: 255
      unique: false
      nullable: true
      column: restore_link
    active:
      type: boolean
      unique: false
      nullable: false
      options:
        default: true
    assetsOpened:
      type: integer
      unique: false
      nullable: false
      options:
        default: 0
      column: assets_opened
    assetsCreated:
      type: integer
      unique: false
      nullable: false
      options:
        default: 0
      column: assets_created
    createdAt:
      type: datetime
      unique: false
      nullable: false
      column: created_at
      gedmo:
        timestampable:
          on: create
    updatedAt:
      type: datetime
      unique: false
      nullable: true
      column: updated_at
      gedmo:
        timestampable:
          on: update
    lastOnline:
      type: datetime
      unique: false
      nullable: true
      column: last_online
    password:
      type: string
      unique: false
      nullable: false
    rememberToken:
      type: string
      unique: false
      nullable: true
      column: remember_token
  manyToMany:
    puzzles:
      targetEntity: Scandinaver\Learning\Puzzle\Domain\Entity\Puzzle
      cascade: { }
      fetch: LAZY
      mappedBy: null
      inversedBy: users
      joinTable:
        name: puzzle_user
        schema: null
        joinColumns:
          - name: user_id
            referencedColumnName: id
            onDelete: CASCADE
        inverseJoinColumns:
          - name: puzzle_id
            referencedColumnName: id
            onDelete: CASCADE
      orderBy: null
    roles:
      targetEntity: Scandinaver\RBAC\Domain\Entity\Role
      cascade: { }
      fetch: EAGER
      joinTable:
        name: user_role
        joinColumns:
          user_id:
            referencedColumnName: id
            onDelete: CASCADE
        inverseJoinColumns:
          role_id:
            referencedColumnName: id
      orderBy: null
    permissions:
      targetEntity: Scandinaver\RBAC\Domain\Entity\Permission
      cascade: { }
      fetch: EAGER
      joinTable:
        name: user_permission
        joinColumns:
          user_id:
            referencedColumnName: id
            onDelete: CASCADE
        inverseJoinColumns:
          permission_id:
            referencedColumnName: id
      orderBy: null
    texts:
      targetEntity: Scandinaver\Learning\Translate\Domain\Entity\Text
      cascade: { }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinTable:
        name: text_user
        schema: null
        joinColumns:
          - name: user_id
            referencedColumnName: id
            onDelete: CASCADE
        inverseJoinColumns:
          - name: text_id
            referencedColumnName: id
            onDelete: CASCADE
      orderBy: null
  oneToMany:
    posts:
      targetEntity: Scandinaver\Blog\Domain\Entity\Post
      cascade: { }
      fetch: LAZY
      mappedBy: user
      inversedBy: null
      orphanRemoval: false
      orderBy: null
    personalAssets:
      targetEntity: Scandinaver\Learning\Asset\Domain\Entity\Asset
      cascade:
        - persist
      fetch: LAZY
      mappedBy: owner
      joinColumns:
        id:
          referencedColumnName: owner_id
      orderBy:
        category: DESC
    assetPassings:
      targetEntity: Scandinaver\Learning\Asset\Domain\Entity\Passing
      cascade:
        - persist
      fetch: LAZY
      mappedBy: user
      joinColumns:
        id:
          referencedColumnName: user_id
      orderBy: null
    textPassings:
      targetEntity: Scandinaver\Learning\Translate\Domain\Entity\Passing
      cascade:
        - persist
      fetch: LAZY
      mappedBy: user
      joinColumns:
        id:
          referencedColumnName: user_id
      orderBy: null
    orders:
      targetEntity: Scandinaver\Billing\Domain\Entity\Order
      cascade:
        - persist
      fetch: LAZY
      mappedBy: user
      joinColumns:
        id:
          referencedColumnName: user_id
      orderBy: null
  lifecycleCallbacks: { }
