Scandinaver\Settings\Domain\Entity\Setting:
  type: entity
  table: settings
  indexes:
    title:
      columns:
        - title
    slug:
      columns:
        - slug
  id:
    id:
      type: integer
      nullable: false
      id: true
      generator:
        strategy: IDENTITY
  fields:
    title:
      type: string
      length: 255
      unique: true
      nullable: false
    slug:
      type: string
      length: 255
      unique: true
      nullable: false
    data:
      type: json
      nullable: false
    description:
      type: text
      unique: false
      nullable: true
    createdAt:
      type: datetime
      unique: false
      nullable: false
      column: created_at
      gedmo:
        timestampable:
          on: create
    updatedAt:
      type: datetime
      length: null
      unique: false
      nullable: true
      column: updated_at
      gedmo:
        timestampable:
          on: update
  lifecycleCallbacks: { }
