<?php


namespace Scandinaver\User\Application\Provider;

use Illuminate\Foundation\Support\Providers\EventServiceProvider as ServiceProvider;

/**
 * Class EventServiceProvider
 *
 * @package Scandinaver\User\Application\Provider
 *
 * THIS CLASS IS AUTOGENERATED. DONT CHANGE IT MANUALLY.
 */
class EventServiceProvider extends ServiceProvider
{
    protected $listen = [
        'Scandinaver\User\Domain\Event\UserCreated' => [
            'Scandinaver\User\Domain\Event\Listener\UserCreatedListener',
        ],
        'Scandinaver\User\Domain\Event\UserDeleted' => [
            'Scandinaver\User\Domain\Event\Listener\UserDeletedListener',
        ],
    ];

    public function boot()
    {
        parent::boot();
    }
}