Scandinaver\RBAC\Domain\Entity\Permission:
  type: entity
  table: permission
  id:
    id:
      type: integer
      nullable: false
      id: true
      generator:
        strategy: IDENTITY
  fields:
    name:
      type: string
      length: 255
      unique: true
      nullable: false
    slug:
      type: string
      length: 255
      unique: true
      nullable: false
    description:
      type: text
      unique: false
      nullable: true
    updatedAt:
      type: datetime
      nullable: false
      column: updated_at
      gedmo:
        timestampable:
          on: update
    createdAt:
      type: datetime
      unique: false
      nullable: true
      column: created_at
      gedmo:
        timestampable:
          on: create
  manyToOne:
    group:
      targetEntity: Scandinaver\RBAC\Domain\Entity\PermissionGroup
      cascade: { }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        permission_group_id:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: { }
