<?php


namespace Scandinaver\Blog\Infrastructure;

use Illuminate\Foundation\Support\Providers\EventServiceProvider as ServiceProvider;

/**
 * Class EventServiceProvider
 *
 * @package Scandinaver\Blog\Infrastructure
 *
 * THIS CLASS IS AUTOGENERATED. DONT CHANGE IT MANUALLY.
 */
class EventServiceProvider extends ServiceProvider
{
    protected $listen = [
        'Scandinaver\Blog\Domain\Events\CategoryDeleted' => [
            'Scandinaver\Blog\Domain\Events\Listeners\CategoryDeletedListener',
        ],
        'Scandinaver\Blog\Domain\Events\CategoryNameUpdated' => [
            'Scandinaver\Blog\Domain\Events\Listeners\CategoryNameUpdatedListener',
        ],
        'Scandinaver\Blog\Domain\Events\CommentAdded' => [
            'Scandinaver\Blog\Domain\Events\Listeners\CommentAddedListener',
        ],
    ];

    public function boot()
    {
        parent::boot();
    }
}