Scandinaver\Common\Domain\Entity\Language:
  type: entity
  table: language
  indexes:
    letter:
      columns:
        - letter
    id:
      columns:
        - id
  id:
    id:
      type: integer
      nullable: false
      id: true
      generator:
        strategy: IDENTITY
  fields:
    letter:
      type: string
      length: 5
      unique: false
      nullable: false
    title:
      type: string
      length: 50
      unique: false
      nullable: false
    flag:
      type: string
      length: 255
      unique: false
      nullable: false
    image:
      type: string
      length: 255
      unique: false
      nullable: false
    description:
      type: text
      unique: false
      nullable: true
  lifecycleCallbacks: { }
