Scandinaver\Common\Domain\Entity\Log:
  type: entity
  table: log
  indexes:
    id:
      columns:
        - id
  id:
    id:
      type: integer
      nullable: false
      id: true
      generator:
        strategy: IDENTITY
  fields:
    message:
      type: text
      unique: false
      nullable: false
    level:
      type: integer
      length: 1
      unique: false
      nullable: true
    levelName:
      type: string
      length: 255
      unique: false
      nullable: true
    context:
      type: array
      unique: false
      nullable: true
    extra:
      type: array
      unique: false
      nullable: true
    createdAt:
      type: datetime
      unique: false
      nullable: false
      column: created_at
      gedmo:
        timestampable:
          on: create
  manyToOne:
    owner:
      targetEntity: Scandinaver\User\Domain\Entity\User
      cascade: [ "persist", "merge" ]
      fetch: LAZY
      joinColumns:
        occured_on:
          referencedColumnName: id
      orphanRemoval: false
      orderBy: null
      nullable: true
  lifecycleCallbacks: { }
