<?php


namespace Scandinaver\Statistic\Application\Provider;

use Illuminate\Foundation\Support\Providers\EventServiceProvider as ServiceProvider;

/**
 * Class EventServiceProvider
 *
 * @package Scandinaver\Statistic\Application\Provider
 *
 * THIS CLASS IS AUTOGENERATED. DONT CHANGE IT MANUALLY.
 *
 * php artisan scandinaver:event
 * php artisan scandinaver:rebuild:events Statistic
 */
class EventServiceProvider extends ServiceProvider
{
    protected $listen = [
        'Scandinaver\Statistic\Domain\Event\Test' => [
            'Scandinaver\Statistic\Domain\Event\Listener\TestListener',
        ],
    ];

    protected $subscribe = [
        
    ];

    public function boot()
    {
        parent::boot();
    }
}