<?php


namespace Scandinaver\Statistic\Application\Provider;

use Illuminate\Foundation\Support\Providers\EventServiceProvider as ServiceProvider;
use Scandinaver\Statistic\Application\Subscriber\AssetEventsSubscriber;
use Scandinaver\Statistic\Application\Subscriber\PuzzleEventsSubscriber;
use Scandinaver\Statistic\Application\Subscriber\UserEventsSubscriber;

/**
 * Class EventServiceProvider
 *
 * @package Scandinaver\Statistic\Application\Provider
 *
 * THIS CLASS IS AUTOGENERATED. DONT CHANGE IT MANUALLY.
 *
 * php artisan scandinaver:event
 * php artisan scandinaver:rebuild:events Statistic
 */
class EventServiceProvider extends ServiceProvider
{
    protected $listen = [

    ];

    protected $subscribe = [
        AssetEventsSubscriber::class,
        UserEventsSubscriber::class,
        PuzzleEventsSubscriber::class,
    ];
}