Scandinaver\Settings\Domain\Model\Setting:
  type: entity
  table: settings
  indexes:
    title:
      columns:
        - title
    slug:
      columns:
        - slug
  id:
    id:
      type: integer
      scale: 0
      length: null
      unique: false
      nullable: false
      precision: 0
      id: true
      generator:
        strategy: IDENTITY
  fields:
    title:
      type: string
      scale: 0
      length: 255
      unique: true
      nullable: false
      precision: 0
    slug:
      type: string
      scale: 0
      length: 255
      unique: true
      nullable: false
      precision: 0
    data:
      type: json
      nullable: false
    createdAt:
      type: datetime
      scale: 0
      length: null
      unique: false
      nullable: true
      precision: 0
      column: created_at
      gedmo:
        timestampable:
          on: create
    updatedAt:
      type: datetime
      scale: 0
      length: null
      unique: false
      nullable: true
      precision: 0
      column: updated_at
      gedmo:
        timestampable:
          on: update
  lifecycleCallbacks: { }
