<?php


namespace Scandinaver\Learning\Puzzle\Application\Provider;

use Illuminate\Foundation\Support\Providers\EventServiceProvider as ServiceProvider;

/**
 * Class EventServiceProvider
 *
 * @package Scandinaver\Learning\Puzzle\Application\Provider
 *
 * THIS CLASS IS AUTOGENERATED. DONT CHANGE IT MANUALLY.
 */
class EventServiceProvider extends ServiceProvider
{
    protected $listen = [
        'Scandinaver\Learning\Puzzle\Domain\Event\PuzzleCreated' => [
            'Scandinaver\Learning\Puzzle\Domain\Event\Listener\PuzzleCreatedListener',
        ],
        'Scandinaver\Learning\Puzzle\Domain\Event\TestCreated' => [
            'Scandinaver\Learning\Puzzle\Domain\Event\Listener\TestCreatedListener',
        ],
    ];

    public function boot()
    {
        parent::boot();
    }
}