<?php


namespace Scandinaver\Learning\Asset\Application\Provider;

use Illuminate\Foundation\Support\Providers\EventServiceProvider as ServiceProvider;
use Scandinaver\Learning\Asset\Application\Subscriber\LanguageEventsSubscriber;
use Scandinaver\Learning\Asset\Application\Subscriber\UserEventsSubscriber;

/**
 * Class EventServiceProvider
 *
 * @package Scandinaver\Learning\Asset\Application\Provider
 *
 * THIS CLASS IS AUTOGENERATED. DONT CHANGE IT MANUALLY.
 */
class EventServiceProvider extends ServiceProvider
{
    protected $listen = [
        'Scandinaver\Learning\Asset\Domain\Event\AssetCreated' => [
            'Scandinaver\Learning\Asset\Domain\Event\Listener\AssetCreatedListener',
        ],
        'Scandinaver\Learning\Asset\Domain\Event\AssetDeleted' => [
            'Scandinaver\Learning\Asset\Domain\Event\Listener\AssetDeletedListener',
        ],
        'Scandinaver\Learning\Asset\Domain\Event\CardAddedToAsset' => [
            'Scandinaver\Learning\Asset\Domain\Event\Listener\CardAddedToAssetListener',
        ],
        'Scandinaver\Learning\Asset\Domain\Event\CardRemovedFromAsset' => [
            'Scandinaver\Learning\Asset\Domain\Event\Listener\CardRemovedFromAssetListener',
        ],
        'Scandinaver\Learning\Asset\Domain\Event\TermUpdated' => [
            'Scandinaver\Learning\Asset\Domain\Event\Listener\TermUpdatedListener',
        ],
        'Scandinaver\Learning\Asset\Domain\Event\TranslateUpdated' => [
            'Scandinaver\Learning\Asset\Domain\Event\Listener\TranslateUpdatedListener',
        ],
    ];

    public function boot()
    {
        parent::boot();
    }

    protected $subscribe = [
        UserEventsSubscriber::class,
        LanguageEventsSubscriber::class,
    ];
}