<?php


namespace Scandinaver\Learn\Application\Provider;

use Illuminate\Foundation\Support\Providers\EventServiceProvider as ServiceProvider;

/**
 * Class EventServiceProvider
 *
 * @package Scandinaver\Learn\Application\Provider
 *
 * THIS CLASS IS AUTOGENERATED. DONT CHANGE IT MANUALLY.
 */
class EventServiceProvider extends ServiceProvider
{
    protected $listen = [
        'Scandinaver\Learn\Domain\Event\AssetCreated'         => [
            'Scandinaver\Learn\Domain\Event\Listener\AssetCreatedListener',
        ],
        'Scandinaver\Learn\Domain\Event\AssetDeleted'         => [
            'Scandinaver\Learn\Domain\Event\Listener\AssetDeletedListener',
        ],
        'Scandinaver\Learn\Domain\Event\CardAddedToAsset'     => [
            'Scandinaver\Learn\Domain\Event\Listener\CardAddedToAssetListener',
        ],
        'Scandinaver\Learn\Domain\Event\CardRemovedFromAsset' => [
            'Scandinaver\Learn\Domain\Event\Listener\CardRemovedFromAssetListener',
        ],
        'Scandinaver\Learn\Domain\Event\TranslateUpdated'     => [
            'Scandinaver\Learn\Domain\Event\Listener\TranslateUpdatedListener',
        ],
        'Scandinaver\Learn\Domain\Event\WordUpdated'          => [
            'Scandinaver\Learn\Domain\Event\Listener\WordUpdatedListener',
        ],
    ];

    public function boot()
    {
        parent::boot();
    }
}