<?php


namespace Scandinaver\Common\Application\Provider;

use Illuminate\Foundation\Support\Providers\EventServiceProvider as ServiceProvider;

/**
 * Class EventServiceProvider
 *
 * @package Scandinaver\Common\Application\Provider
 *
 * THIS CLASS IS AUTOGENERATED. DONT CHANGE IT MANUALLY.
 */
class EventServiceProvider extends ServiceProvider
{
    protected $listen = [
        'Scandinaver\Common\Domain\Event\LanguageCreated' => [
            'Scandinaver\Common\Domain\Event\Listener\LanguageCreatedListener',
        ],
        'Scandinaver\Common\Domain\Event\LanguageDeleted' => [
            'Scandinaver\Common\Domain\Event\Listener\LanguageDeletedListener',
        ],
        'Scandinaver\Common\Domain\Event\LanguageUpdated' => [
            'Scandinaver\Common\Domain\Event\Listener\LanguageUpdatedListener',
        ],
    ];

    public function boot()
    {
        parent::boot();
    }
}