Scandinaver\RBAC\Domain\Entity\PermissionGroup:
  type: entity
  table: permission_group
  id:
    id:
      type: integer
      nullable: false
      id: true
      generator:
        strategy: IDENTITY
  fields:
    name:
      type: string
      length: 255
      unique: true
      nullable: false
    slug:
      type: string
      length: 255
      unique: true
      nullable: false
    description:
      type: text
      unique: false
      nullable: true
    createdAt:
      type: datetime
      unique: false
      nullable: false
      column: created_at
      gedmo:
        timestampable:
          on: create
    updatedAt:
      type: datetime
      unique: false
      nullable: true
      column: updated_at
      gedmo:
        timestampable:
          on: update
  lifecycleCallbacks: { }
