Scandinaver\RBAC\Domain\Entity\Role:
  type: entity
  table: role
  id:
    id:
      type: integer
      nullable: false
      id: true
      generator:
        strategy: IDENTITY
  fields:
    name:
      type: string
      length: 255
      unique: true
      nullable: false
    slug:
      type: string
      length: 255
      unique: true
      nullable: false
    description:
      type: text
      unique: false
      nullable: true
    createdAt:
      type: datetime
      unique: false
      nullable: false
      column: created_at
      gedmo:
        timestampable:
          on: create
    updatedAt:
      type: datetime
      unique: false
      nullable: true
      column: updated_at
      gedmo:
        timestampable:
          on: update
  manyToMany:
    permissions:
      targetEntity: Scandinaver\RBAC\Domain\Entity\Permission
      joinTable:
        name: role_permission
        joinColumns:
          role_id:
            referencedColumnName: id
        inverseJoinColumns:
          permission_id:
            referencedColumnName: id
      cascade: { }
      fetch: EAGER
      orphanRemoval: false
      orderBy: null
  lifecycleCallbacks: { }
