Scandinaver\Common\Domain\Entity\Feedback:
  type: entity
  table: message
  id:
    id:
      type: integer
      unique: false
      id: true
      generator:
        strategy: IDENTITY
  fields:
    name:
      type: string
      length: 255
      unique: false
      nullable: false
    message:
      type: text
      unique: false
      nullable: false
    readed:
      type: boolean
      unique: false
      nullable: false
      options:
        default: false
    createdAt:
      type: datetime
      unique: false
      nullable: false
      column: created_at
      gedmo:
        timestampable:
          on: create
    updatedAt:
      type: datetime
      unique: false
      nullable: true
      column: updated_at
      gedmo:
        timestampable:
          on: update
  lifecycleCallbacks: { }
