Scandinaver\Common\Domain\Entity\Intro:
  type: entity
  table: intro
  id:
    id:
      type: integer
      nullable: false
      id: true
      generator:
        strategy: IDENTITY
  fields:
    page:
      type: string
      length: 255
      unique: false
      nullable: false
    target:
      type: string
      length: 255
      unique: false
      nullable: true
    content:
      type: text
      unique: false
      nullable: false
    header:
      type: string
      length: 255
      unique: false
      nullable: true
    position:
      type: string
      length: 255
      unique: false
      nullable: false
    sort:
      type: integer
      unique: false
      nullable: false
      options:
        default: 0
    active:
      type: boolean
      unique: false
      nullable: false
      options:
        default: false
    createdAt:
      type: datetime
      unique: false
      nullable: false
      column: created_at
      gedmo:
        timestampable:
          on: create
    updatedAt:
      type: datetime
      unique: false
      nullable: true
      column: updated_at
      gedmo:
        timestampable:
          on: update
  lifecycleCallbacks: { }
