Scandinaver\User\Domain\Entity\OauthAuthCode:
  type: entity
  table: oauth_auth_codes
  id:
    id:
      type: string
      length: 100
      unique: false
      nullable: false
      id: true
  fields:
    userId:
      type: integer
      unique: false
      nullable: false
      column: user_id
    clientId:
      type: integer
      unique: false
      nullable: false
      column: client_id
    scopes:
      type: text
      unique: false
      nullable: true
    revoked:
      type: boolean
      unique: false
      nullable: false
    expiresAt:
      type: datetime
      unique: false
      nullable: true
      column: expires_at
  lifecycleCallbacks: { }
