Scandinaver\User\Domain\Model\OauthAccessToken:
    type: entity
    table: oauth_access_tokens
    indexes:
        user_id_token_index:
            columns:
                - user_id
    id:
        id:
            type: string
            scale: 0
            length: 100
            unique: false
            nullable: false
            precision: 0
            id: true
    fields:
        userId:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: user_id
        clientId:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            column: client_id
        name:
            type: string
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
        scopes:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
        revoked:
            type: boolean
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        createdAt:
            type: datetime
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            column: created_at
        updatedAt:
            type: datetime
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: updated_at
        expiresAt:
            type: datetime
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: expires_at
    lifecycleCallbacks: {  }
