Scandinaver\User\Domain\Entity\OauthPersonalAccessClient:
  type: entity
  table: oauth_personal_access_clients
  indexes:
    client_id_index:
      columns:
        - client_id
  id:
    id:
      type: integer
      nullable: false
      id: true
      generator:
        strategy: IDENTITY
  fields:
    clientId:
      type: integer
      unique: false
      nullable: false
      column: client_id
    createdAt:
      type: datetime
      unique: false
      nullable: true
      column: created_at
    updatedAt:
      type: datetime
      unique: false
      nullable: true
      column: updated_at
  lifecycleCallbacks: { }
