Scandinaver\User\Domain\Entity\OauthClients:
  type: entity
  table: oauth_clients
  indexes:
    user_id_client_index:
      columns:
        - user_id
  id:
    id:
      type: integer
      nullable: false
      id: true
      generator:
        strategy: IDENTITY
  fields:
    userId:
      type: integer
      unique: false
      nullable: true
      column: user_id
    name:
      type: string
      unique: false
      nullable: false
    secret:
      type: string
      length: 100
      unique: false
      nullable: false
    redirect:
      type: text
      unique: false
      nullable: false
    personalAccessClient:
      type: boolean
      unique: false
      nullable: false
      column: personal_access_client
    passwordClient:
      type: boolean
      unique: false
      nullable: false
      column: password_client
    revoked:
      type: boolean
      unique: false
      nullable: false
    createdAt:
      type: datetime
      unique: false
      nullable: true
      column: created_at
    updatedAt:
      type: datetime
      unique: false
      nullable: true
      column: updated_at
  lifecycleCallbacks: { }
