Scandinaver\User\Domain\Model\OauthClients:
  type: entity
  table: oauth_clients
  indexes:
    user_id_client_index:
      columns:
        - user_id
  id:
    id:
      type: integer
      scale: 0
      length: null
      unique: false
      nullable: false
      precision: 0
      id: true
      generator:
        strategy: IDENTITY
  fields:
    userId:
      type: integer
      scale: 0
      length: null
      unique: false
      nullable: true
      precision: 0
      column: user_id
    name:
      type: string
      scale: 0
      length: null
      unique: false
      nullable: false
      precision: 0
    secret:
      type: string
      scale: 0
      length: 100
      unique: false
      nullable: false
      precision: 0
    redirect:
      type: text
      scale: 0
      length: null
      unique: false
      nullable: false
      precision: 0
    personalAccessClient:
      type: boolean
      scale: 0
      length: null
      unique: false
      nullable: false
      precision: 0
      column: personal_access_client
    passwordClient:
      type: boolean
      scale: 0
      length: null
      unique: false
      nullable: false
      precision: 0
      column: password_client
    revoked:
      type: boolean
      scale: 0
      length: null
      unique: false
      nullable: false
      precision: 0
    createdAt:
      type: datetime
      scale: 0
      length: null
      unique: false
      nullable: true
      precision: 0
      column: created_at
    updatedAt:
      type: datetime
      scale: 0
      length: null
      unique: false
      nullable: true
      precision: 0
      column: updated_at
  lifecycleCallbacks: { }
