Scandinaver\User\Domain\Entity\Order:
  type: entity
  table: order
  indexes:
    user_id:
      columns:
        - user_id
    plan_id:
      columns:
        - plan_id
  id:
    id:
      type: integer
      nullable: false
      id: true
      generator:
        strategy: IDENTITY
  fields:
    sum:
      type: integer
      unique: false
      nullable: false
    status:
      type: string
      length: 50
      unique: false
      nullable: true
    notificationType:
      type: string
      length: 255
      unique: false
      nullable: true
      column: notification_type
    datetime:
      type: string
      length: 255
      unique: false
      nullable: true
    codepro:
      type: string
      length: 255
      unique: false
      nullable: true
    sender:
      type: string
      length: 255
      unique: false
      nullable: true
    sha1Hash:
      type: string
      length: 255
      unique: false
      nullable: true
      column: sha1_hash
    label:
      type: string
      length: 255
      unique: false
      nullable: true
    createdAt:
      type: datetime
      length: null
      unique: false
      nullable: true
      column: created_at
    updatedAt:
      type: datetime
      length: null
      unique: false
      nullable: true
      column: updated_at
  manyToOne:
    plan:
      targetEntity: Scandinaver\User\Domain\Entity\Plan
      cascade: { }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        plan_id:
          referencedColumnName: id
      orphanRemoval: false
    user:
      targetEntity: Scandinaver\User\Domain\Entity\User
      cascade: { }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        user_id:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: { }
