Scandinaver\User\Domain\Entity\Plan:
  type: entity
  table: plan
  id:
    id:
      type: integer
      nullable: false
      id: true
      generator:
        strategy: IDENTITY
  fields:
    name:
      type: string
      length: 50
      unique: false
      nullable: false
    period:
      type: string
      length: 50
      unique: false
      nullable: false
    cost:
      type: integer
      unique: false
      nullable: true
    costPerMonth:
      type: integer
      unique: false
      nullable: true
      column: cost_per_month
  lifecycleCallbacks: { }
