<?php

namespace DoctrineProxies\__CG__\Scandinaver\Translate\Domain;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Text extends \Scandinaver\Translate\Domain\Text implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Scandinaver\\Translate\\Domain\\Text' . "\0" . 'id', '' . "\0" . 'Scandinaver\\Translate\\Domain\\Text' . "\0" . 'languageId', '' . "\0" . 'Scandinaver\\Translate\\Domain\\Text' . "\0" . 'level', '' . "\0" . 'Scandinaver\\Translate\\Domain\\Text' . "\0" . 'title', '' . "\0" . 'Scandinaver\\Translate\\Domain\\Text' . "\0" . 'description', '' . "\0" . 'Scandinaver\\Translate\\Domain\\Text' . "\0" . 'text', '' . "\0" . 'Scandinaver\\Translate\\Domain\\Text' . "\0" . 'translate', '' . "\0" . 'Scandinaver\\Translate\\Domain\\Text' . "\0" . 'published', '' . "\0" . 'Scandinaver\\Translate\\Domain\\Text' . "\0" . 'createdAt', '' . "\0" . 'Scandinaver\\Translate\\Domain\\Text' . "\0" . 'updatedAt', '' . "\0" . 'Scandinaver\\Translate\\Domain\\Text' . "\0" . 'image', '' . "\0" . 'Scandinaver\\Translate\\Domain\\Text' . "\0" . 'users', '' . "\0" . 'Scandinaver\\Translate\\Domain\\Text' . "\0" . 'language', '' . "\0" . 'Scandinaver\\Translate\\Domain\\Text' . "\0" . 'extra', '' . "\0" . 'Scandinaver\\Translate\\Domain\\Text' . "\0" . 'words', '' . "\0" . 'Scandinaver\\Translate\\Domain\\Text' . "\0" . 'textResults', '' . "\0" . 'Scandinaver\\Translate\\Domain\\Text' . "\0" . 'synonims'];
        }

        return ['__isInitialized__', '' . "\0" . 'Scandinaver\\Translate\\Domain\\Text' . "\0" . 'id', '' . "\0" . 'Scandinaver\\Translate\\Domain\\Text' . "\0" . 'languageId', '' . "\0" . 'Scandinaver\\Translate\\Domain\\Text' . "\0" . 'level', '' . "\0" . 'Scandinaver\\Translate\\Domain\\Text' . "\0" . 'title', '' . "\0" . 'Scandinaver\\Translate\\Domain\\Text' . "\0" . 'description', '' . "\0" . 'Scandinaver\\Translate\\Domain\\Text' . "\0" . 'text', '' . "\0" . 'Scandinaver\\Translate\\Domain\\Text' . "\0" . 'translate', '' . "\0" . 'Scandinaver\\Translate\\Domain\\Text' . "\0" . 'published', '' . "\0" . 'Scandinaver\\Translate\\Domain\\Text' . "\0" . 'createdAt', '' . "\0" . 'Scandinaver\\Translate\\Domain\\Text' . "\0" . 'updatedAt', '' . "\0" . 'Scandinaver\\Translate\\Domain\\Text' . "\0" . 'image', '' . "\0" . 'Scandinaver\\Translate\\Domain\\Text' . "\0" . 'users', '' . "\0" . 'Scandinaver\\Translate\\Domain\\Text' . "\0" . 'language', '' . "\0" . 'Scandinaver\\Translate\\Domain\\Text' . "\0" . 'extra', '' . "\0" . 'Scandinaver\\Translate\\Domain\\Text' . "\0" . 'words', '' . "\0" . 'Scandinaver\\Translate\\Domain\\Text' . "\0" . 'textResults', '' . "\0" . 'Scandinaver\\Translate\\Domain\\Text' . "\0" . 'synonims'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Text $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getTitle(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitle', []);

        return parent::getTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitle(string $title): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitle', [$title]);

        parent::setTitle($title);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription(?string $description): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getImage(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImage', []);

        return parent::getImage();
    }

    /**
     * {@inheritDoc}
     */
    public function setImage(?string $image): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImage', [$image]);

        parent::setImage($image);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsers()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsers', []);

        return parent::getUsers();
    }

    /**
     * {@inheritDoc}
     */
    public function getId(): int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function jsonSerialize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'jsonSerialize', []);

        return parent::jsonSerialize();
    }

    /**
     * {@inheritDoc}
     */
    public function setSynonims(array $data): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSynonims', [$data]);

        parent::setSynonims($data);
    }

    /**
     * {@inheritDoc}
     */
    public function getLevel(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLevel', []);

        return parent::getLevel();
    }

}
