<?php

namespace DoctrineProxies\__CG__\Scandinaver\Blog\Domain;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Post extends \Scandinaver\Blog\Domain\Post implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Scandinaver\\Blog\\Domain\\Post' . "\0" . 'id', '' . "\0" . 'Scandinaver\\Blog\\Domain\\Post' . "\0" . 'title', '' . "\0" . 'Scandinaver\\Blog\\Domain\\Post' . "\0" . 'userId', '' . "\0" . 'Scandinaver\\Blog\\Domain\\Post' . "\0" . 'content', '' . "\0" . 'Scandinaver\\Blog\\Domain\\Post' . "\0" . 'categoryId', '' . "\0" . 'Scandinaver\\Blog\\Domain\\Post' . "\0" . 'anonse', '' . "\0" . 'Scandinaver\\Blog\\Domain\\Post' . "\0" . 'status', '' . "\0" . 'Scandinaver\\Blog\\Domain\\Post' . "\0" . 'commentStatus', '' . "\0" . 'Scandinaver\\Blog\\Domain\\Post' . "\0" . 'views', '' . "\0" . 'Scandinaver\\Blog\\Domain\\Post' . "\0" . 'updatedAt', '' . "\0" . 'Scandinaver\\Blog\\Domain\\Post' . "\0" . 'createdAt', '' . "\0" . 'Scandinaver\\Blog\\Domain\\Post' . "\0" . 'deletedAt', '' . "\0" . 'Scandinaver\\Blog\\Domain\\Post' . "\0" . 'comments', '' . "\0" . 'Scandinaver\\Blog\\Domain\\Post' . "\0" . 'user', '' . "\0" . 'Scandinaver\\Blog\\Domain\\Post' . "\0" . 'category', '' . "\0" . 'Scandinaver\\Blog\\Domain\\Post' . "\0" . 'language'];
        }

        return ['__isInitialized__', '' . "\0" . 'Scandinaver\\Blog\\Domain\\Post' . "\0" . 'id', '' . "\0" . 'Scandinaver\\Blog\\Domain\\Post' . "\0" . 'title', '' . "\0" . 'Scandinaver\\Blog\\Domain\\Post' . "\0" . 'userId', '' . "\0" . 'Scandinaver\\Blog\\Domain\\Post' . "\0" . 'content', '' . "\0" . 'Scandinaver\\Blog\\Domain\\Post' . "\0" . 'categoryId', '' . "\0" . 'Scandinaver\\Blog\\Domain\\Post' . "\0" . 'anonse', '' . "\0" . 'Scandinaver\\Blog\\Domain\\Post' . "\0" . 'status', '' . "\0" . 'Scandinaver\\Blog\\Domain\\Post' . "\0" . 'commentStatus', '' . "\0" . 'Scandinaver\\Blog\\Domain\\Post' . "\0" . 'views', '' . "\0" . 'Scandinaver\\Blog\\Domain\\Post' . "\0" . 'updatedAt', '' . "\0" . 'Scandinaver\\Blog\\Domain\\Post' . "\0" . 'createdAt', '' . "\0" . 'Scandinaver\\Blog\\Domain\\Post' . "\0" . 'deletedAt', '' . "\0" . 'Scandinaver\\Blog\\Domain\\Post' . "\0" . 'comments', '' . "\0" . 'Scandinaver\\Blog\\Domain\\Post' . "\0" . 'user', '' . "\0" . 'Scandinaver\\Blog\\Domain\\Post' . "\0" . 'category', '' . "\0" . 'Scandinaver\\Blog\\Domain\\Post' . "\0" . 'language'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Post $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getComments()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComments', []);

        return parent::getComments();
    }

    /**
     * {@inheritDoc}
     */
    public function setComments($comments): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComments', [$comments]);

        parent::setComments($comments);
    }

    /**
     * {@inheritDoc}
     */
    public function jsonSerialize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'jsonSerialize', []);

        return parent::jsonSerialize();
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt(): ?\DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function getUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', []);

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser($user): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', [$user]);

        parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategory(): \Scandinaver\Blog\Domain\Category
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategory', []);

        return parent::getCategory();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategory(\Scandinaver\Blog\Domain\Category $category): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategory', [$category]);

        parent::setCategory($category);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitle(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitle', []);

        return parent::getTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitle(string $title): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitle', [$title]);

        parent::setTitle($title);
    }

    /**
     * {@inheritDoc}
     */
    public function setContent(?string $content): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContent', [$content]);

        parent::setContent($content);
    }

}
