Scandinaver\Learning\Asset\Domain\Entity\Card:
  type: entity
  table: cards
  indexes:
    term_id:
      columns:
        - term_id
    translate_id:
      columns:
        - translate_id
  id:
    id:
      type: integer
      nullable: false
      id: true
      generator:
        strategy: IDENTITY
  fields:
    type:
      type: integer
      unique: false
      nullable: false
      column: type
    createdAt:
      type: datetime
      unique: false
      nullable: false
      column: created_at
      gedmo:
        timestampable:
          on: create
    updatedAt:
      type: datetime
      unique: false
      nullable: true
      column: updated_at
      gedmo:
        timestampable:
          on: update
  manyToOne:
    term:
      targetEntity: Scandinaver\Learning\Asset\Domain\Entity\Term
      cascade: [ "persist", "merge" ]
      fetch: EAGER
      joinColumns:
        term_id:
          referencedColumnName: id
      orphanRemoval: false
    translate:
      targetEntity: Scandinaver\Learning\Asset\Domain\Entity\Translate
      cascade: [ "persist", "merge" ]
      fetch: EAGER
      mappedBy: null
      inversedBy: null
      joinColumns:
        translate_id:
          referencedColumnName: id
      orphanRemoval: false
    language:
      targetEntity: Scandinaver\Common\Domain\Entity\Language
      cascade: { }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        language_id:
          referencedColumnName: id
      orphanRemoval: false
  oneToMany:
    examples:
      targetEntity: Scandinaver\Learning\Asset\Domain\Entity\Example
      cascade: [ "persist", "merge" ]
      fetch: EAGER
      mappedBy: card
      inversedBy: null
      joinColumns:
        card_id:
          referencedColumnName: id
      orphanRemoval: true
      orderBy: null
  #manyToMany:
  #    assets:
  #        targetEntity:  Scandinaver\Learning\Asset\Domain\Entity\Asset
  #        joinTable:
  #            name: asset_cards
  #            joinColumns:
  #                asset_id:
  #                    referencedColumnName: id
  #            inverseJoinColumns:
  #                card_id:
  #                    referencedColumnName: id
  #


  lifecycleCallbacks: { }
