Scandinaver\Learning\Asset\Domain\Entity\Passing:
  type: entity
  table: test_result
  indexes:
    user_id:
      columns:
        - user_id
    asset_id:
      columns:
        - asset_id
  id:
    id:
      type: integer
      nullable: false
      id: true
      generator:
        strategy: IDENTITY
  fields:
    completed:
      type: boolean
      unique: false
      nullable: false
    percent:
      type: integer
      unique: false
      nullable: false
    data:
      type: json
      nullable: false
    createdAt:
      type: datetime
      unique: false
      nullable: false
      column: created_at
      gedmo:
        timestampable:
          on: create
    updatedAt:
      type: datetime
      unique: false
      nullable: true
      column: updated_at
      gedmo:
        timestampable:
          on: update
  manyToOne:
    subject:
      targetEntity: Scandinaver\Learning\Asset\Domain\Entity\Asset
      cascade:
        - persist
      fetch: LAZY
      mappedBy: null
      inversedBy: passings
      joinColumns:
        asset_id:
          referencedColumnName: id
          onDelete: CASCADE
      orphanRemoval: false
    language:
      targetEntity: Scandinaver\Common\Domain\Entity\Language
      cascade: { }
      fetch: LAZY
      mappedBy: language
      joinColumns:
        language_id:
          referencedColumnName: id
      orphanRemoval: false
    user:
      targetEntity: Scandinaver\User\Domain\Entity\User
      cascade: { }
      fetch: LAZY
      inversedBy: assetPassings
      joinColumns:
        user_id:
          referencedColumnName: id
          onDelete: CASCADE
      orphanRemoval: false
  lifecycleCallbacks: { }
