Scandinaver\Learning\Asset\Domain\Entity\Translate:
  type: entity
  table: translate
  indexes:
    term_id:
      columns:
        - term_id
    fulltext:
      columns:
        - value
  id:
    id:
      type: integer
      nullable: false
      id: true
      generator:
        strategy: IDENTITY
  fields:
    value:
      type: string
      length: 255
      unique: false
      nullable: false
    sentence:
      type: boolean
      unique: false
      nullable: false
    createdAt:
      type: datetime
      unique: false
      nullable: false
      column: created_at
      gedmo:
        timestampable:
          on: create
    updatedAt:
      type: datetime
      unique: false
      nullable: true
      column: updated_at
      gedmo:
        timestampable:
          on: update
  manyToOne:
    term:
      targetEntity: Scandinaver\Learning\Asset\Domain\Entity\Term
      cascade:
        - persist
      fetch: LAZY
      mappedBy: null
      inversedBy: translates
      joinColumns:
        term_id:
          referencedColumnName: id
      orphanRemoval: false
    language:
      targetEntity: Scandinaver\Common\Domain\Entity\Language
      cascade: { }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        language_id:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: { }
