Scandinaver\Translate\Domain\Entity\Result:
  type: entity
  table: result_text
  indexes:
    user_id:
      columns:
        - user_id
    text_id:
      columns:
        - text_id
  id:
    id:
      type: integer
      nullable: false
      id: true
      generator:
        strategy: IDENTITY
  fields:
    textId:
      type: integer
      length: null
      unique: false
      nullable: false
      column: text_id
    createdAt:
      type: datetime
      length: null
      unique: false
      nullable: false
      column: created_at
      gedmo:
        timestampable:
          on: create
    updatedAt:
      type: datetime
      length: null
      unique: false
      nullable: true
      column: updated_at
      gedmo:
        timestampable:
          on: update
  manyToOne:
    language:
      targetEntity: Scandinaver\Common\Domain\Entity\Language
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        language_id:
          referencedColumnName: id
      orphanRemoval: false
    user:
      targetEntity: Scandinaver\User\Domain\Entity\User
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: translates
      joinColumns:
        user_id:
          referencedColumnName: id
      orphanRemoval: false
    text:
      targetEntity: Scandinaver\Translate\Domain\Entity\Text
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: textResults
      joinColumns:
        text_id:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: {  }
