Scandinaver\Translate\Domain\Model\Result:
  type: entity
  table: result_text
  indexes:
    user_id:
      columns:
        - user_id
    text_id:
      columns:
        - text_id
  id:
    id:
      type: integer
      scale: 0
      length: null
      unique: false
      nullable: false
      precision: 0
      id: true
      generator:
        strategy: IDENTITY
  fields:
    textId:
      type: integer
      scale: 0
      length: null
      unique: false
      nullable: false
      precision: 0
      column: text_id
    createdAt:
      type: datetime
      scale: 0
      length: null
      unique: false
      nullable: false
      precision: 0
      column: created_at
    updatedAt:
      type: datetime
      scale: 0
      length: null
      unique: false
      nullable: true
      precision: 0
      column: updated_at
  manyToOne:
    language:
      targetEntity: Scandinaver\Common\Domain\Model\Language
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        language_id:
          referencedColumnName: id
      orphanRemoval: false
    user:
      targetEntity: Scandinaver\User\Domain\Model\User
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        user_id:
          referencedColumnName: id
      orphanRemoval: false
    text:
      targetEntity: Scandinaver\Translate\Domain\Model\Text
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: textResults
      joinColumns:
        text_id:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: {  }
