Scandinaver\Translate\Domain\Entity\Synonym:
  type: entity
  table: synonym
  indexes:
    word_id:
      columns:
        - word_id
        - synonym
  id:
    id:
      type: integer
      nullable: false
      id: true
      generator:
        strategy: IDENTITY
  fields:
    synonym:
      type: string
      length: 255
      unique: false
      nullable: false
    createdAt:
      type: datetime
      unique: false
      nullable: false
      column: created_at
      gedmo:
        timestampable:
          on: create
    updatedAt:
      type: datetime
      unique: false
      nullable: true
      column: updated_at
      gedmo:
        timestampable:
          on: update
  manyToOne:
    word:
      targetEntity: Scandinaver\Translate\Domain\Entity\Word
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: synonyms
      joinColumns:
        word_id:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: {  }
