Scandinaver\Translate\Domain\Model\Synonym:
  type: entity
  table: synonym
  indexes:
    word_id:
      columns:
        - word_id
        - synonym
  id:
    id:
      type: integer
      scale: 0
      length: null
      unique: false
      nullable: false
      precision: 0
      id: true
      generator:
        strategy: IDENTITY
  fields:
    synonym:
      type: string
      scale: 0
      length: 255
      unique: false
      nullable: false
      precision: 0
    createdAt:
      type: datetime
      scale: 0
      length: null
      unique: false
      nullable: false
      precision: 0
      column: created_at
    updatedAt:
      type: datetime
      scale: 0
      length: null
      unique: false
      nullable: true
      precision: 0
      column: updated_at
  manyToOne:
    word:
      targetEntity: Scandinaver\Translate\Domain\Model\Word
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: synonyms
      joinColumns:
        word_id:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: {  }
