Scandinaver\Translate\Domain\Entity\Tooltip:
  type: entity
  table: text__tooltip
  indexes:
    text_id:
      columns:
        - text_id
        - object
        - value
    IDX_3317FC22698D3548:
      columns:
        - text_id
  id:
    id:
      type: integer
      nullable: false
      id: true
      generator:
        strategy: IDENTITY
  fields:
    object:
      type: string
      length: 255
      unique: false
      nullable: false
    value:
      type: string
      length: 255
      unique: false
      nullable: false
    createdAt:
      type: datetime
      unique: false
      nullable: false
      column: created_at
      gedmo:
        timestampable:
          on: create
    updatedAt:
      type: datetime
      unique: false
      nullable: true
      column: updated_at
      gedmo:
        timestampable:
          on: update
  manyToOne:
    text:
      targetEntity: Scandinaver\Translate\Domain\Entity\Text
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: tooltips
      joinColumns:
        text_id:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: {  }
