Scandinaver\Translate\Domain\Entity\Word:
  type: entity
  table: word_in_text
  indexes:
    text_id:
      columns:
        - text_id
        - sentence_num
        - word
    IDX_1B42EF50698D3548:
      columns:
        - text_id
  id:
    id:
      type: integer
      nullable: false
      id: true
      generator:
        strategy: IDENTITY
  fields:
    sentenceNum:
      type: integer
      unique: false
      nullable: false
      column: sentence_num
    word:
      type: string
      length: 255
      unique: false
      nullable: false
    orig:
      type: string
      length: 255
      unique: false
      nullable: true
    createdAt:
      type: datetime
      unique: false
      nullable: false
      column: created_at
      gedmo:
        timestampable:
          on: create
    updatedAt:
      type: datetime
      unique: false
      nullable: true
      column: updated_at
      gedmo:
        timestampable:
          on: update
  manyToOne:
    text:
      targetEntity: Scandinaver\Translate\Domain\Entity\Text
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: words
      joinColumns:
        text_id:
          referencedColumnName: id
      orphanRemoval: false
  oneToMany:
    synonyms:
      targetEntity: Scandinaver\Translate\Domain\Entity\Synonym
      cascade: {  }
      fetch: LAZY
      mappedBy: word
      inversedBy: null
      orphanRemoval: false
  lifecycleCallbacks: {  }
