<?php


namespace Scandinaver\Puzzle\Application\Provider;

use Illuminate\Foundation\Support\Providers\EventServiceProvider as ServiceProvider;

/**
 * Class EventServiceProvider
 *
 * @package Scandinaver\Puzzle\Application\Provider
 *
 * THIS CLASS IS AUTOGENERATED. DONT CHANGE IT MANUALLY.
 */
class EventServiceProvider extends ServiceProvider
{
    protected $listen = [
        'Scandinaver\Puzzle\Domain\Event\PuzzleCreated' => [
            'Scandinaver\Puzzle\Domain\Event\Listener\PuzzleCreatedListener',
        ],
        'Scandinaver\Puzzle\Domain\Event\TestCreated'   => [
            'Scandinaver\Puzzle\Domain\Event\Listener\TestCreatedListener',
        ],
    ];

    public function boot()
    {
        parent::boot();
    }
}