<?php


namespace Scandinaver\Learn\Application\Providers;

use Illuminate\Foundation\Support\Providers\EventServiceProvider as ServiceProvider;

/**
 * Class EventServiceProvider
 *
 * @package Scandinaver\Learn\Application\Providers
 *
 * THIS CLASS IS AUTOGENERATED. DONT CHANGE IT MANUALLY.
 */
class EventServiceProvider extends ServiceProvider
{
    protected $listen = [
        'Scandinaver\Learn\Domain\Events\AssetCreated' => [
            'Scandinaver\Learn\Domain\Events\Listeners\AssetCreatedListener',
        ],
        'Scandinaver\Learn\Domain\Events\AssetDeleted' => [
            'Scandinaver\Learn\Domain\Events\Listeners\AssetDeletedListener',
        ],
        'Scandinaver\Learn\Domain\Events\CardAddedToAsset' => [
            'Scandinaver\Learn\Domain\Events\Listeners\CardAddedToAssetListener',
        ],
        'Scandinaver\Learn\Domain\Events\CardRemovedFromAsset' => [
            'Scandinaver\Learn\Domain\Events\Listeners\CardRemovedFromAssetListener',
        ],
        'Scandinaver\Learn\Domain\Events\TranslateUpdated' => [
            'Scandinaver\Learn\Domain\Events\Listeners\TranslateUpdatedListener',
        ],
        'Scandinaver\Learn\Domain\Events\WordUpdated' => [
            'Scandinaver\Learn\Domain\Events\Listeners\WordUpdatedListener',
        ],
    ];

    public function boot()
    {
        parent::boot();
    }
}