Scandinaver\Blog\Domain\Entity\Category:
  type: entity
  table: category
  indexes:
    name:
      columns:
        - title
  id:
    id:
      type: integer
      nullable: false
      id: true
      generator:
        strategy: IDENTITY
  fields:
    title:
      type: string
      length: 255
      unique: false
      nullable: false
    createdAt:
      type: datetime
      unique: false
      nullable: false
      column: created_at
      gedmo:
        timestampable:
          on: create
    updatedAt:
      type: datetime
      unique: false
      nullable: true
      column: updated_at
      gedmo:
        timestampable:
          on: update
  lifecycleCallbacks: { }
