Scandinaver\Blog\Domain\Entity\Post:
  type: entity
  table: post
  indexes:
    post_name:
      columns:
        - title
    post_author:
      columns:
        - user_id
    id:
      columns:
        - id
  id:
    id:
      type: integer
      nullable: false
      id: true
      generator:
        strategy: IDENTITY
  fields:
    title:
      type: string
      length: 200
      unique: false
      nullable: false
    content:
      type: text
      unique: false
      nullable: true
    anonse:
      type: text
      unique: false
      nullable: true
    status:
      type: boolean
      unique: false
      nullable: false
      options:
        default: false
    commentStatus:
      type: boolean
      unique: false
      nullable: false
      options:
        default: true
      column: comment_status
    views:
      type: integer
      unique: false
      nullable: false
      options:
        default: 0
    createdAt:
      type: datetime
      unique: false
      nullable: false
      column: created_at
      gedmo:
        timestampable:
          on: create
    updatedAt:
      type: datetime
      unique: false
      nullable: true
      column: updated_at
      gedmo:
        timestampable:
          on: update
  oneToMany:
    comments:
      targetEntity: Scandinaver\Blog\Domain\Entity\Comment
      cascade: { }
      fetch: EAGER
      mappedBy: post
      inversedBy: null
      orphanRemoval: false
      orderBy: null
  manyToOne:
    user:
      targetEntity: Scandinaver\User\Domain\Entity\User
      cascade: { }
      fetch: LAZY
      mappedBy: null
      inversedBy: posts
      joinColumns:
        user_id:
          referencedColumnName: id
      orphanRemoval: false
    category:
      targetEntity: Scandinaver\Blog\Domain\Entity\Category
      cascade: { }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        category_id:
          referencedColumnName: id
      orphanRemoval: false
    language:
      targetEntity: Scandinaver\Common\Domain\Entity\Language
      cascade: { }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        language_id:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: { }
