<?php


namespace Scandinaver\Reader\Infrastructure;

use Illuminate\Support\ServiceProvider;

/**
 * Class ReaderServiceProvider
 *
 * @package Scandinaver\Reader\Infrastructure
 *
 * THIS CLASS IS AUTOGENERATED. DONT CHANGE IT MANUALLY.
 */
class ReaderServiceProvider extends ServiceProvider
{
    public function register()
    {
        /** COMMAND **/
        

        /** QUERY **/
        $this->app->bind(
            'ReadCardHandlerInterface',
            'Scandinaver\Reader\Application\Handler\Query\ReadCardHandler'
        );

        $this->app->bind(
            'ReadHandlerInterface',
            'Scandinaver\Reader\Application\Handler\Query\ReadHandler'
        );
    }
}